{
    "name": "Employee Shift Management",
    "version": "19.0.1.0.0",
    "summary": "Create shifts, assign employees and view shifts in a calendar",
    "category": "Human Resources",
    "author": "Auto Generated",
    "website": "",
    "license": "LGPL-3",
    "depends": ["base", "hr", "hr_holidays", "hr_attendance", "calendar"],
    "data": [
        "security/employee_shift_security.xml",
        "security/ir.model.access.csv",
        "views/shift_template_views.xml",
        "views/dashboard_action.xml",
        "views/employee_shift_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "employee_shift/static/src/utils/tz_utils.js",
            "employee_shift/static/src/dashboard/dashboard.js",
            "employee_shift/static/src/dashboard/dashboard.xml",
            "employee_shift/static/src/add_shift_modal/add_shift_modal.js",
            "employee_shift/static/src/add_shift_modal/add_shift_modal.xml",
            "employee_shift/static/src/dashboard/dashboard.scss",
        ],
    },
    "post_init_hook": "employee_shift_post_init",
    "installable": True,
    "application": True,
}
