{
    "name": "Tuition Management",
    "version": "19.0.2.0",
    "summary": "Manage tuition courses, students, tutors and registrations",
    "category": "Education",
    "author": "Auto Generated",
    "website": "",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "portal",
        "website",
        "account",
        "sale",
        "base_setup",
    ],
    "data": [
        "security/virtual_classroom_security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "views/master_views.xml",
        "views/profile_views.xml",
        "views/course_views.xml",
        "views/schedule_views.xml",
        "views/virtual_classroom_views.xml",
        "views/virtual_classroom_settings_views.xml",
        "views/tutor_payroll_views.xml",
        "views/attendance_views.xml",
        "views/progress_views.xml",
        "views/tuition_views.xml",
        "views/billing_views.xml",
        "views/parent_billing_run_views.xml",
        "views/menu_views.xml",
        "views/report_class_status_views.xml",
        "views/report_subject_wise_views.xml",
        "views/report_tutor_wise_views.xml",
        "views/report_views.xml",
        "views/tuition_billing_views.xml",
        "views/portal_css.xml",
        "views/portal_layout.xml",
        "views/portal_common.xml",
        "views/portal_student_views.xml",
        "views/portal_tutor_views.xml",
        "views/portal_parent_views.xml",
        "views/portal_templates.xml",
        "views/portal_public_enquiry.xml",
        "views/product_views.xml",
    ],
    "demo": [
        "data/report_demo_data.xml",
    ],
    "installable": True,
    "application": True,
    "post_init_hook": "_create_default_enquiry_stages",
    "assets": {
        "web.assets_backend": [
            "tuition_management/static/src/dashboard/dashboard.js",
            "tuition_management/static/src/dashboard/dashboard.xml",
        ],
    },
}
