{
    "name": "Tuition Management",
    "version": "19.0.1.7",
    "summary": "Manage tuition courses, students, tutors and registrations",
    "category": "Education",
    "author": "Auto Generated",
    "website": "",
    "license": "LGPL-3",
    "depends": [
        "base",
        "portal",
        "website",
        "account",
        "sale",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "views/tuition_views.xml",
        "views/tuition_billing_views.xml",
        "views/portal_css.xml",
        "views/portal_layout.xml",
        "views/portal_common.xml",
        "views/portal_student_views.xml",
        "views/portal_tutor_views.xml",
        "views/portal_parent_views.xml",
        "views/portal_templates.xml",
    ],
    "installable": True,
    "application": True,
    "post_init_hook": "_create_default_enquiry_stages",
    "assets": {
        "web.assets_backend": [
            "tuition_management/static/src/dashboard/dashboard.js",
            "tuition_management/static/src/dashboard/dashboard.xml",
        ],
    },
}
